export const adminSettingsCategories = [
  { key: 'general', name: '通用' },
  { key: 'auth', name: '认证' },
  { key: 'security', name: '安全' },
  { key: 'cors', name: 'CORS' },
  { key: 'billing', name: '计费/订阅' },
  { key: 'oauth', name: 'OAuth' },
  { key: 'email', name: '邮件' },
  { key: 'smtp', name: 'SMTP' },
  { key: 'logging', name: '日志' },
  { key: 'session', name: '会话' },
  { key: 'ui', name: '外观/品牌' },
  { key: 'uploads', name: '上传' },
  { key: 'notifications', name: '通知' },
  { key: 'jwt', name: 'JWT' },
  { key: 'cache', name: '缓存' },
  { key: 'storage', name: '存储' },
  { key: 'features', name: '特性开关' },
  { key: 'maintenance', name: '维护模式' },
  { key: 'analytics', name: '统计分析' },
  { key: 'captcha', name: '验证码' },
  { key: 'webhooks', name: 'Webhooks' },
  { key: 'audit', name: '审计' },
  { key: 'pagination', name: '分页' },
]
