export const adminSettingsCategories = [
  { key: 'general', name: 'translated' },
  { key: 'auth', name: 'translated' },
  { key: 'security', name: 'security' },
  { key: 'cors', name: 'CORS' },
  { key: 'billing', name: 'translated/subscription' },
  { key: 'oauth', name: 'OAuth' },
  { key: 'email', name: 'translated' },
  { key: 'smtp', name: 'SMTP' },
  { key: 'logging', name: 'translated' },
  { key: 'session', name: 'session' },
  { key: 'ui', name: 'translated/translated' },
  { key: 'uploads', name: 'translated' },
  { key: 'notifications', name: 'notification' },
  { key: 'jwt', name: 'JWT' },
  { key: 'cache', name: 'translated' },
  { key: 'storage', name: 'translated' },
  { key: 'features', name: 'translated' },
  { key: 'maintenance', name: 'translated' },
  { key: 'analytics', name: 'translated' },
  { key: 'captcha', name: 'verification code' },
  { key: 'webhooks', name: 'Webhooks' },
  { key: 'audit', name: 'translated' },
  { key: 'pagination', name: 'translated' },
]
