services:
  backend:
    image: ${BACKEND_IMAGE}
    restart: unless-stopped
    expose:
      - "8101"
    volumes:
      - data:/data
    env_file:
      - .env

  frontend:
    image: ${FRONTEND_IMAGE}
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  data:
