openapi: 3.0.3
info:
  title: BasaltPass API
  version: 0.1.0
servers:
  - url: http://localhost:8080
paths:
  /api/v1/auth/register:
    post:
      summary: Register new user
      responses:
        '501':
          description: Not implemented
  /api/v1/auth/login:
    post:
      summary: User login
      responses:
        '501':
          description: Not implemented
  /api/v1/auth/refresh:
    post:
      summary: Refresh access token
      responses:
        '401':
          description: Unauthorized
        '200':
          description: New access token
  /api/v1/user/profile:
    get:
      summary: Get user profile
      responses:
        '200':
          description: User profile
    put:
      summary: Update user profile
      responses:
        '204':
          description: Updated
  /api/v1/wallet/balance:
    get:
      summary: Get wallet balance
      responses:
        '200':
          description: Balance
  /api/v1/wallet/recharge:
    post:
      summary: Recharge wallet (mock)
      responses:
        '204':
          description: Recharged
  /api/v1/wallet/withdraw:
    post:
      summary: Withdraw funds (mock)
      responses:
        '204':
          description: Withdrawn
  /api/v1/wallet/history:
    get:
      summary: Transaction history
      responses:
        '200':
          description: List
  /api/v1/security/2fa/setup:
    post:
      summary: Setup TOTP secret
      responses:
        '200':
          description: Secret created
  /api/v1/security/2fa/verify:
    post:
      summary: Verify TOTP code
      responses:
        '204':
          description: Verified 
  /api/v1/auth/password/reset-request:
    post:
      summary: Request password reset code
      responses:
        '200':
          description: Code generated
  /api/v1/auth/password/reset:
    post:
      summary: Reset password with code
      responses:
        '204':
          description: Password updated 
  /api/v1/admin/roles:
    get:
      summary: List roles
      responses:
        '200':
          description: Role list
    post:
      summary: Create role
      responses:
        '201':
          description: Role created
  /api/v1/admin/user/{id}/role:
    post:
      summary: Assign role to user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Assigned 